### ISSUE TITLE
Multiple installer defects on Linux

### ISSUE THREAD

**Issue by bonachea** [rouson/caffeine#14]
The following log is from my failed attempts to naively follow the caffeine installation instructions at 3679c9f on a node of our Scientific Linux cluster. This is admittedly an old distribution, but is representative of the oldest Linux environment your users are likely to encounter in the field.

```
$ uname -a
Linux pcp-d-5 3.10.0-693.1.1.el7.x86_64 #1 SMP Tue Aug 15 08:36:44 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="Scientific Linux"
VERSION="7.3 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.3"
PRETTY_NAME="Scientific Linux 7.3 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.3:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
$ git status
# On branch main
nothing to commit, working directory clean
$ git describe --always
3679c9f
$ git --version
git version 1.8.3.1
$ ./install.sh --help
./install.sh: Command not found.
$ head ./install.sh 
#!/bin/dash

$ ls /bin/dash
/bin/ls: cannot access /bin/dash: No such file or directory
$ /bin/sh ./install.sh --help         
Caffeine Installation Script

USAGE:
./install.sh [--help | [--prefix=PREFIX]

 --help             Display this help text
 --prefix=PREFIX    Install binary in 'PREFIX/bin'
                    Default prefix='$HOME/.local/bin'

$ /bin/sh ./install.sh --prefix=`pwd`/inst
The version of Git that was found does not satisfy requirements for Homebrew.
$ module switch git git/2.24.1 
$ git --version
git version 2.24.1
$ /bin/sh ./install.sh --prefix=`pwd`/inst
==> Found Git: /usr/local/pkg/git/2.24.1/bin/git
The version of cURL that was found does not satisfy requirements for Homebrew.
Please install cURL 7.41.0 or newer and add it to your PATH.
```

This is the point at which I gave up. 

This reveals several defects in the current installer:
1. It assumes `/bin/dash` is portably available everywhere - it is not. 
     * Instead:  `/bin/sh` is always safe. `/bin/bash` is common, but not universal.
     * For an example of one approach to portably handle the "shell bootstrap problem" see the top 40 lines of [upcxx/configure](https://bitbucket.org/berkeleylab/upcxx/src/master/configure), which portably establishes a bash environment with a given bash floor version.
2. It hard-codes the compiler names `gcc-11`, `g++-11` and `gfortran-11`, and when any are missing goes down a path to install them. These names are common but not universal, even on a system with gcc-11.x installed (it depends on gcc install options). On my example system above, version 11.2.0 for all three was available via barenames `gcc`, `g++` and `gfortran`
     * Instead: Documentation should clarify supported compiler versions. There should be a mechanism for the user to specify the name/path of the required compilers satisfying those dependencies (the conventional mechanism being envvars: `$CC`, `$CXX`, `$FC`), and failure to find commands meeting the requirements should produce a message. The same is technically true for other required commands, although it's far less common for things like `make` and `pkg-config` to only be available under a non-standard name.
3. It *silently* attempts to install unrelated dependency software (brew, compilers, coreutils) on the local machine without any prompting, with the similarly silent assumption that brew is the preferred package manager. This is a pretty serious violation of user trust. 
     * Instead: Required dependencies should be loudly documented in the README, and failure to find them should produce a message asking the user for guidance in finding them, or possibly *offering* to attempt automated installation via brew. If the latter requires escalated privilege (sudo), this should be clarified in the message.

**Comment by rouson** [comment]
Thanks, @bonachea.  I'll investigate item 1.  Regarding item 2, those are the names for the required compilers after they are installed by homebrew.  For simplicity, I'd like to consider homebrew-installed compilers as the only supported compilers for now on  both macOS and Linux. If this effort is able to add sufficient staffing or attract contributors to support other installation methods, that would be great, but it's important to note that this code is a *really* long ways from being usable by anyone other than Caffeine contributors.  I'll update the README.md to clarify that at the top. To be usable more broadly will first require that Caffeine be adopted as the parallel runtime library for one or more compilers.  The two most likely candidates are LLFM/flang and LFortran, neither of which is ready to choose a parallel runtime library yet because they aren't ready to work on supporting Fortran 2008/2018 parallel features.   In fact, main branch/fork of flang can't compile _anything_ yet.  There's an ongoing process of merging a branch that will hopefully soon enable flang to produce executables for the first time ever and that will just be for Fortran 95.  Then they'll work on Fortran 2003 so Fortran 2008/2018 support is quite a ways away.

The goal here is to get ready well in advance of when flang and LFortran get to the point of choosing a parallel runtime library.  For now, the potential user community is in the single digits and will likely stay that way for at least 1-2 years.

Regarding 3, I'll change the installer to prompt the user for permission before installing anything other than Caffeine itself.

**Comment by rouson** [comment]
@bonachea I believe all issues mentioned here are addressed in the pull request that I just merged into the main branch of the BerkeleyLab fork so I'll close this issue here.  The closed PR shows Linux CI tests passing and the macOS test logs show the installer running to completion without error, but for some reason the  macOS CI process hangs until being killed after 360 minutes. The installer works for me locally both in macOS and inside a Linux virtual machine so hopefully we're all set.
